[package]
name = "toaster_lib_rs"
version = "0.1.0"
edition = "2024"

[dependencies]

colored = "*"
anyhow = "*"
uuid = "*"

serde = {version = "*", features = ["derive", "rc"]}
bytesize = "*"

http = {version = "*"}

tokio = {version = "*", features = ["full"]}
log = "*"
bytes = "*"

sequoia-openpgp = {version = "*"}
rand = "*"
futures = "*"

tonic = "*"
prost = "0.14"
tonic-prost = "*"

[build-dependencies]

tonic-prost-build = "*"
