syntax = "proto3";

package invoker_manager;

import "toaster.proto";

enum AuthVerdict {
  AUTH_VERDICT_UNSPECIFIED = 0;
  AUTH_VERDICT_APPROVED = 1;
  AUTH_VERDICT_DENIED = 2;
}
message CloseInvoker {}

message Exited {
  uint32 code = 1;
  string message = 2; // exit data
}

message TestResultPayload {
  uint32 id = 1;
  toaster.TestResult result = 2;
  bytes data = 3; // tar: (output, message)
}

message SubmissionResult {
  toaster.SubmissionVerdict verdict = 1;

  oneof details {
    SuccessDetails success = 2;
    ErrorDetails error = 3;
  }

  message SuccessDetails {
    uint32 score = 1;
    repeated uint32 group_scores = 2;
  }

  message ErrorDetails {
    string message = 1;
  }
}

message Error {
  string message = 1;
}

message RunTask {
  toaster.Lang lang = 2;
  bytes data = 3; // binary data: problem package
}

message StopTask {}
message AuthChallenge {
  bytes data = 1;
}

message AuthProof {
  bytes data = 1;
}

message CertName {
  string name = 1;
}

message MasterOutgo {
  oneof payload {
    CloseInvoker close = 1;
  }
}

message MasterIncome {
  oneof payload {
    Exited exited = 6;
  }
}

message JudgeOutgo {
  oneof payload {
    RunTask run = 1;
    StopTask stop = 2;
  }
}

message JudgeIncome {
  oneof payload {
    TestResultPayload test_result_payload = 2;
    SubmissionResult submission_result = 3;
    Error error = 4;
  }
}

message AuthOutgo {
  oneof payload {
    AuthChallenge challenge = 1;
    AuthVerdict verdict = 2;
  }
}

message AuthIncome {
  oneof payload {
    CertName cert_name = 1;
    AuthProof proof = 2;
  }
}

// ==========================================
// gRPC Service Definition
// ==========================================

service InvokerManagerService {
  rpc MasterStream(stream MasterIncome) returns (stream MasterOutgo);
  rpc JudgeStream(stream JudgeIncome) returns (stream JudgeOutgo);
  rpc Auth(stream AuthIncome) returns (stream AuthOutgo);
}
